# Generated by Django 3.0.14 on 2023-05-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_product_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
