# Generated by Django 3.2.19 on 2023-05-31 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_customer_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='MyAccountManager',
        ),
    ]
