<<<<<<< HEAD
# Generated by Django 4.2.1 on 2023-06-01 01:47
=======
# Generated by Django 4.2.1 on 2023-06-01 02:23
>>>>>>> dung

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_auto_20230531_1211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
