# Generated by Django 4.2.1 on 2023-06-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
