# Generated by Django 3.2.19 on 2023-06-05 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_reviewrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
