# Generated by Django 3.2.19 on 2023-06-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_comment_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
