# Generated by Django 3.2.19 on 2023-06-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_auto_20230606_1538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
