# Generated by Django 5.0.3 on 2024-04-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0023_auto_20230606_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='star_rating',
            field=models.IntegerField(default=0),
        ),
    ]
