# Generated by Django 5.0.3 on 2024-04-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0024_product_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='star_rating',
            field=models.FloatField(default=0),
        ),
    ]
