# Generated by Django 5.0.3 on 2024-05-20 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0028_review'),
        ('my_app', '0032_auto_20240516_2222'),
    ]

    operations = [
    ]
