# Generated by Django 3.2.19 on 2024-05-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0035_auto_20240520_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='star_rating',
        ),
    ]
