# Generated by Django 3.2.19 on 2024-05-21 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0038_alter_myuser_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
