# Generated by Django 3.2.19 on 2024-05-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0033_merge_0028_review_0032_auto_20240516_2222'),
        ('my_app', '0042_alter_myuser_last_login'),
    ]

    operations = [
    ]
