# Generated by Django 5.0.3 on 2024-05-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0033_merge_0028_review_0032_auto_20240516_2222'),
        ('my_app', '0043_review'),
    ]

    operations = [
    ]
