# Generated by Django 3.2.19 on 2024-05-21 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0044_auto_20240521_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='star_rating',
        ),
    ]
