# Generated by Django 3.2.19 on 2024-05-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0045_remove_product_star_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='star_rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
