# Generated by Django 3.2.19 on 2024-05-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0044_merge_20240521_1656'),
        ('my_app', '0046_product_star_rating'),
    ]

    operations = [
    ]
