# Generated by Django 3.2.19 on 2024-05-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0047_merge_20240523_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('message', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
