# Generated by Django 3.2.19 on 2024-05-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0049_contact_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
