# Generated by Django 3.2.19 on 2024-05-27 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0044_merge_20240522_2039'),
        ('my_app', '0050_delete_contact'),
    ]

    operations = [
    ]
