# Generated by Django 5.0.3 on 2024-06-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0051_merge_0044_merge_20240522_2039_0050_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
