# Generated by Django 3.2.19 on 2024-06-03 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0055_alter_myuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
