# Generated by Django 3.2.19 on 2024-06-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0059_alter_userprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
    ]
